### ISSUE TITLE
Composer.lock shouldn't be part of repository for libraries

### ISSUE THREAD

**Issue by amansilla** [Flagbit/Magento2-Flysystem#11]
**Describe the bug**
`composer.lock` shouldn't be part of repository for libraries for avoiding dependency hell issues on projects using this package.

**Comment by flagbird** [comment]
There are different approaches about the lock-file. Some voices are suggesting to keep this file even for libs. How is Magento handling composer.lock?

**Comment by amansilla** [comment]
@claudioflagbit Can you please, tell me who is suggesting to keep the `composer.lock` in file inside the repository? Because for me that makes no sense since installing this library on any Magento project more than probably would avoid the package to be installed because of dependencies incompatibilities. Until today I didn't see any competent library containing a composer.lock inside the repo, I just would like to understand why.

**Comment by flagbird** [comment]
I'm for "keep lock out of libs" too, but if Magento is keeping it and if it is for a reason, I want to know why. That's why I asked that question.

Some say it is harmless, while others make it depend on how the build strategy of a lib looks like:
https://github.com/composer/composer/issues/2461#issuecomment-29282932
In some cases it is used to prevent failing builds because of dependency BC breaks, but I don't know how well the dependencies of this lib are using Semver. I was in a discussion about this topic 2 years ago and it was quite interesting. But it didn't make me push the lock-file. :-)

**Comment by flagbird** [comment]
Flysystem itself has a fix version in composer.json, so I think removing shouldn't be much of a problem in this lib's use case.
